name: Dependencies

on:
  schedule:
    - cron: "15 9 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: renovatebot/github-action@v43.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
